### ISSUE TITLE
MH-z19b does not support this... you will be stuck for ages here :(

### ISSUE THREAD

**Issue by Eldenroot** [crisap94/MHZ19#12] opened 2020-04-12 15:17 UTC
https://github.com/crisap94/MHZ19/blob/7d3722823cda89d9d6471fb0336bffb4b075aa1b/examples/MHZ19_getppm/MHZ19_getppm.ino#L23

**Comment by crisap94** [comment] 2020-12-13 23:59
Duplicate of #14

**Closed as completed by crisap94** 2020-12-13 23:59 UTC
Labels: bug
