### ISSUE TITLE
status: 0

### ISSUE THREAD

**Issue by willt32** [crisap94/MHZ19#17] opened 2020-12-08 06:02 UTC
hello,

originally had a error of "no response from mh z19"
but i changed the wiring from 5v --> vout, to 5v --> vin

now it says "warming up... status:0"

have left it on for around 10 min. any idea whats going on?
should i have not changed the wiring? but it did not work before. 

rx and tx is connected to the D6 and D7 pins on the esp8266 nodeMCU
any help would be nice

**Comment by crisap94** [comment] 2020-12-14 00:09
Hi @willt32 this seems to be an error with the library, as soon the fix is available the library will get the update, feel free to try what @cbwatts mention on Issue #14.

**Comment by crisap94** [comment] 2020-12-14 00:09
Duplicate of #14

**Closed as completed by crisap94** 2020-12-14 00:09 UTC
